### ISSUE TITLE
OAuth2 Support

### ISSUE THREAD

**Issue by bryceadams** [SocialiteProviders/Fitbit#1]
https://dev.fitbit.com/docs/oauth2/ now available. I'm going to implement it tomorrow :)

**Comment by DraperStudio** [comment]
Is the OAuth 1.0 API now deprecated or still supported? If it is still available and won't be deprecated we would need to have two branches.

**Comment by bryceadams** [comment]
Doesn't look to be officially depreciated yet, so I agree their should be two branches.

**Comment by bryceadams** [comment]
Does this look okay @DraperStudio? https://github.com/bryceadams/Fitbit/tree/oauth2 - not sure how you'd like me to make PR for it. Let me know.

**Comment by DraperStudio** [comment]
Looks fine from quick looking at it, did you test if you can login?

Will take a closer look later today or tomorrow and move it to a `dev`-branch here on the `Fitbit` repository.

**Comment by bryceadams** [comment]
Yep, working pefectly :-)



Best,Bryce

**Comment by DraperStudio** [comment]
Good, then just send a PR to the `oauth2` branch and I will merge it.

**Comment by DraperStudio** [comment]
Fixed with https://github.com/SocialiteProviders/Fitbit/pull/2
