### ISSUE TITLE
OAuth 2

### ISSUE THREAD

**Issue by alexandrasmith00** [SocialiteProviders/Fitbit#5]
Will there be an update to Oauth 2?

**Comment by DraperStudio** [comment]
You are welcome to send a PR to https://github.com/SocialiteProviders/NewProvider and you can use https://github.com/SocialiteProviders/Generators to speed up the process of building a provider.

If you don't send a PR I will try to take a look at the OAuth 2 stuff tomorrow.

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/Fitbit/tree/oauth2/src

composer require socialiteproviders/fitbit:^1.2
