### ISSUE TITLE
FitBit: Authorization header required

### ISSUE THREAD

**Issue by IamSwap** [SocialiteProviders/Fitbit#9]
Trying to connect fitbit with my laravel app. But after allowing permission I am getting this error.
```
Client error: `POST https://api.fitbit.com/oauth2/token` resulted in a `401 Unauthorized` response:
{"errors":[{"errorType":"invalid_request","message":"Authorization header required. Visit https://dev.fitbit.com/docs/oa (truncated...)
```

Update:
I tried to turn off stateless
```
return Socialite::with('fitbit')->stateless(false)->redirect();
```
But now i am getting this exception:

`InvalidStateException in AbstractProvider.php line 32: `

**Comment by Bigwebmaster** [comment]
I fixed this issue on my fork. I created a pull request to solve this for you.
